export const FETCH_RESULT_START = "FETCH_RESULT_START";
export const FETCH_RESULT_SUCCESS = "FETCH_RESULT_SUCCESS";
export const FETCH_RESULT_FAIL = "FETCH_RESULT_FAIL";


export const FETCH_WAREHOUSE_DETAILS_START = "FETCH_WAREHOUSE_DETAILS_START";
export const FETCH_WAREHOUSE_DETAILS_SUCCESS = "FETCH_WAREHOUSE_DETAILS_SUCCESS";
export const FETCH_WAREHOUSE_DETAILS_FAIL = "FETCH_WAREHOUSE_DETAILS_FAIL";

export const FETCH_MORE_WAREHOUSE_DETAILS_START = "FETCH_MORE_WAREHOUSE_DETAILS_START";
export const FETCH_MORE_WAREHOUSE_DETAILS_SUCCESS = "FETCH_MORE_WAREHOUSE_DETAILS_SUCCESS";
export const FETCH_MORE_WAREHOUSE_DETAILS_FAIL = "FETCH_MORE_WAREHOUSE_DETAILS_FAIL";

export const LOGIN_START="LOGIN_START";
export const LOGIN_SUCCESSS="LOGIN_SUCCESSS";
export const LOGIN_FAIL="LOGIN_FAIL";
export const AUTHENTICATE="AUTHENTICATE";
export const LOGOUT_USER="LOGOUT_USER"

export const SIGNUP_START="SIGNUP_START";
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS";
export const SIGNUP_FAIL="SIGNUP_FAIL";
export const CLEAR_SIGNUP_STATE = "CLEAR_SIGNUP_STATE"


export const GET_ACTIVE_WAREHOUSE_START="GET_ACTIVE_WAREHOUSE_START";
export const GET_ACTIVE_WAREHOUSE_SUCCESS="GET_ACTIVE_WAREHOUSE_SUCCESS";
export const GET_ACTIVE_WAREHOUSE_FAIL="GET_ACTIVE_WAREHOUSE_FAIL";

export const GET_INACTIVE_WAREHOUSE_START="GET_INACTIVE_WAREHOUSE_START";
export const GET_INACTIVE_WAREHOUSE_SUCCESS="GET_INACTIVE_WAREHOUSE_SUCCESS";
export const GET_INACTIVE_WAREHOUSE_FAIL="GET_INACTIVE_WAREHOUSE_FAIL";

export const GET_ARCHIVED_WAREHOUSE_START="GET_ARCHIVED_WAREHOUSE_START";
export const GET_ARCHIVED_WAREHOUSE_SUCCESS="GET_ARCHIVED_WAREHOUSE_SUCCESS";
export const GET_ARCHIVED_WAREHOUSE_FAIL="GET_ARCHIVED_WAREHOUSE_FAIL";

export const UPDATE_SEARCH_STATE="UPDATE_SEARCH_STATE";

export const CHNAGEPW_START="CHNAGEPW_START";
export const CHNAGEPW_SUCCESS="CHNAGEPW_SUCCESS";
export const CHNAGEPW_FAIL="CHNAGEPW_FAIL";

export const GET_USERWAREHOUSES_START="GET_USERWAREHOUSES_START";
export const GET_USERWAREHOUSES_SUCCESS="GET_USERWAREHOUSES_SUCCESS";
export const GET_USERWAREHOUSES_FAIL="GET_USERWAREHOUSES_FAIL";

export const CHANGE_WAREHOUSE_STATUS_START="CHANGE_WAREHOUSE_STATUS_START";
export const CHANGE_WAREHOUSE_STATUS_SUCCESS="CHANGE_WAREHOUSE_STATUS_SUCCESS";
export const CHANGE_WAREHOUSE_STATUS_FAIL="CHANGE_WAREHOUSE_STATUS_FAIL";

export const GET_STATES_LIST = "GET_STATES_LIST";
export const GET_STATES_LIST_SUCCESS = "GET_STATES_LIST_SUCCESS";
