export const LOGIN_REQUEST_SENT = "LOGIN_REQUEST_SENT";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL";

export const LOGOUT_REQUEST_SENT = "LOGOUT_REQUEST_SENT";
export const LOGOUT_REQUEST_SUCCESS = "LOGOUT_REQUEST_SUCCESS";
export const LOGOUT_REQUEST_FAIL = "LOGOUT_REQUEST_FAIL";

export const DASHBOARD_REQUEST_SENT = "DASHBOARD_REQUEST_SENT";
export const DASHBOARD_REQUEST_SUCCESS = "DASHBOARD_REQUEST_SUCCESS";
export const DASHBOARD_REQUEST_FAIL = "DASHBOARD_REQUEST_FAIL";

export const PASSWORD_CHANGE_REQUEST_SENT = "PASSWORD_CHANGE_REQUEST_SENT";
export const PASSWORD_CHANGE_SUCCESS = "PASSWORD_CHANGE_SUCCESS";
export const PASSWORD_CHANGE_FAIL = "PASSWORD_CHANGE_FAIL";
export const PASSWORD_CLEAR_STATE="PASSWORD_CLEAR_STATE"

export const FETCH_RESULTS_STARTS = "FETCH_RESULTS_STARTS";
export const FETCH_RESULTS_SUCCESS = "FETCH_RESULTS_SUCCESS";
export const FETCH_RESULTS_FAILS = "FETCH_RESULTS_FAILS";

export const GET_STATES_LIST = "GET_STATES_LIST";
export const GET_STATES_LIST_SUCCESS = "GET_STATES_LIST_SUCCESS";
